version: '3.8'
services:
  db:
    container_name: pg_container
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      #- ./init_second_db.sql:/docker-entrypoint-initdb.d/init_second_db.sql
  gadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5050:80"
    volumes: 
      - ./pgadmin-data:/var/lib/pgadmin
  nwdaf_sub:
    container_name: nwdaf_sub
    image: thanlinardos/nwdaf_sub:0.0.1-SNAPSHOT
    restart: always
    tty: true
    ports:
      - "${server_port}:${server_port}"
    links:
      - db
    environment:
      SPRING.PROFILES.ACTIVE: production
      nnwdaf-eventsubscription.openapi.dev_url: "${server_host}:${server_port}"
      nnwdaf-eventsubscription.openapi.prod_url: "${server_host}:${server_port}"
      nnwdaf-eventsubscription.client.dev_url: "${client_host}:${client_port}/client"
      nnwdaf-eventsubscription.client.prod_url: "${client_host}:${client_port}/client"
      nnwdaf-eventsubscription.init: false
      nnwdaf-eventsubscription.prometheus_url: http://localhost:9090/api/v1/query
      nnwdaf-eventsubscription.containerNames: pg_container,pgadmin4_container,nwdaf_sub
      SPRING.DATASOURCE.NAME: eventsubscription
      SPRING.DATASOURCE.URL: jdbc:postgresql://db:5432/postgres?currentSchema=public 
      SPRING.DATASOURCE.USERNAME: postgres
      SPRING.DATASOURCE.PASSWORD: password
      SPRING.DATASOURCE.DRIVERCLASSNAME: org.postgresql.Driver
      EVENTNOTIFICATION.DATASOURCE.NAME: eventnotification
      EVENTNOTIFICATION.DATASOURCE.URL: jdbc:postgresql://db:5432/test?currentSchema=public 
      EVENTNOTIFICATION.DATASOURCE.USERNAME: postgres
      EVENTNOTIFICATION.DATASOURCE.PASSWORD: password
      EVENTNOTIFICATION.DATASOURCE.DRIVERCLASSNAME: org.postgresql.Driver
      SERVER.PORT: "${server_port}"
      management.endpoint.health.show-details: always
  nwdaf_sub_client:
    # container_name: nwdaf_sub_client
    image: thanlinardos/nwdaf_sub_client:0.0.1-SNAPSHOT
    restart: always
    tty: true
    ports:
      - "${client_port}:${client_port}"
    environment:
      springdoc.enable-native-support: true
      springdoc.swagger-ui.path: /swagger-ui
      server.port: "${client_port}"
      nnwdaf-eventsubscription.openapi.dev_url: "${server_host}:${server_port}"
      nnwdaf-eventsubscription.openapi.prod_url: "${server_host}:${server_port}"
      nnwdaf-eventsubscription.client.dev_url: "${client_host}:${client_port}/client"
      nnwdaf-eventsubscription.client.prod_url: "${client_host}:${client_port}/client"
      nnwdaf-eventsubscription.init: false
      #spring configuration:
      spring.datasource.generate-unique-name: false
      spring.datasource.name: eventsubscription
      spring.profiles.active: production

      #endpoints:
      management.endpoint.health.show-details: always

      