version: '3.8'
networks:
  monitor-net:
    driver: bridge
name: dockprom
services:
  db:
    container_name: pg_container
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    networks:
      - monitor-net
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      #- ./init_second_db.sql:/docker-entrypoint-initdb.d/init_second_db.sql
  gadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5050:80"
    networks:
      - monitor-net
    volumes: 
      - /home/thanlinardos/Documents/eclipse-workspace-spring/NWDAF_SUB/pgadmin-data:/var/lib/pgadmin
  # influxdb:
  #   image: influxdb:2.6-alpine
  #   env_file:
  #     - influxv2.env
  #   volumes:
  #     # Mount for influxdb data directory and configuration
  #     - ./influxdbv2:/var/lib/influxdb2:rw
  #   networks:
  #     - monitor-net
  #   ports:
  #     - "8086:8086"
  timescaledb:
    image: timescale/timescaledb:latest-pg12
    restart: always
    expose:
    - "5433"
    ports:
      - 5433:5433
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    networks:
      - monitor-net
    volumes:
      - ./timescaledb-data:/var/lib/postgresql/data