version: '3.8'
networks:
  monitor-net:
    driver: bridge
name: dockprom
services:
  db:
    container_name: pg_container
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    networks:
      - monitor-net
    volumes:
      - ../../../../../project-db-files/postgres-data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
  gadmin:
    container_name: pgadmin4_container
    user: root
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5050:80"
    networks:
      - monitor-net
    volumes: 
      - ../../../../../project-db-files/pgadmin-data:/var/lib/pgadmin
  timescaledb:
    image: timescale/timescaledb:latest-pg12
    restart: always
    ports:
      - 5433:5433
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    networks:
      - monitor-net
    command: postgres -c port=5433
    volumes:
      - ../../../../../project-db-files/timescaledb-data:/var/lib/postgresql/data
      - ./timescaleSchema.sql:/docker-entrypoint-initdb.d/timescaleSchema.sql
  redis:
    container_name: redis
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=password
      - REDIS_PORT=6379
      - REDIS_DATABASES=16