version: '3.8'
networks:
  monitor-net:
    driver: bridge
name: dockprom
services:
  nwdafSubCollector:
    container_name: nwdafSubCollector
    image: thanlinardos/nwdaf_sub_collector:0.0.1-SNAPSHOT
    # restart: always
    ports:
      - "${collector_port}:${collector_port}"
      - "5006:5006"
    network_mode: host
    environment:
      server.port: ${collector_port}
      DEBUG_PORT: 5006
      spring.kafka.bootstrap-servers: ${kafka1_host}:${kafka1_port}
      spring.kafka.consumer.group-id: events
      logging.level.org.apache.kafka: false
      nnwdaf-eventsubscription.prometheus_url: http://localhost:${prom_port}/api/v1/query
      nnwdaf-eventsubscription.allow_dummy_data: false
      nnwdaf-eventsubscription.allow_prom_data: true
      nnwdaf-eventsubscription.allow_nef_data: true
      nnwdaf-eventsubscription.no_dummy_nfload: 10
      nnwdaf-eventsubscription.no_dummy_uemob: 10
      nnwdaf-eventsubscription.no_dummy_uecomm: 10
      nnwdaf-eventsubscription.nef_url: https://${nef_host}:${nef_port}/api/v1/
      nnwdaf-eventsubscription.nef_state_ues: ue_movement/state-ues
      nnwdaf-eventsubscription.nef_token: ${nef_token}
    entrypoint: /bin/sh -c
    command: ["java -Xdebug -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:$${DEBUG_PORT} -jar /app.jar"]
  nwdafSubCollector2:
    container_name: nwdafSubCollector2
    image: thanlinardos/nwdaf_sub_collector:0.0.1-SNAPSHOT
    # restart: always
    ports:
      - "${collector_port2}:${collector_port2}"
      - "5012:5012"
    network_mode: host
    environment:
      server.port: ${collector_port2}
      DEBUG_PORT: 5012
      spring.kafka.bootstrap-servers: ${kafka1_host}:${kafka1_port}
      spring.kafka.consumer.group-id: events
      logging.level.org.apache.kafka: false
      nnwdaf-eventsubscription.prometheus_url: http://localhost:${prom_port}/api/v1/query
      nnwdaf-eventsubscription.allow_dummy_data: true
      nnwdaf-eventsubscription.allow_prom_data: false
      nnwdaf-eventsubscription.allow_nef_data: false
      nnwdaf-eventsubscription.no_dummy_nfload: 100
      nnwdaf-eventsubscription.no_dummy_uemob: 100
      nnwdaf-eventsubscription.no_dummy_uecomm: 100
      nnwdaf-eventsubscription.nef_url: https://${nef_host}:${nef_port}/api/v1/
      nnwdaf-eventsubscription.nef_state_ues: ue_movement/state-ues
      nnwdaf-eventsubscription.nef_token: ${nef_token}
    entrypoint: /bin/sh -c
    command: [ "java -Xdebug -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:$${DEBUG_PORT} -jar /app.jar" ]
  nwdafSub:
    container_name: nwdafSub
    image: thanlinardos/nwdaf_sub:0.0.2-SNAPSHOT
    restart: always
    tty: true
    ports:
      - "${server_port}:${server_port}"
      - "5005:5005"
    networks:
      - monitor-net
    environment:
      SPRING.PROFILES.ACTIVE: production
      nnwdaf-eventsubscription.openapi.dev_url: "https://${server_host}:${server_port}"
      nnwdaf-eventsubscription.openapi.prod_url: "https://${server_host}:${server_port}"
      nnwdaf-eventsubscription.client.dev_url: "https://${client_host}:${client_port}/client"
      nnwdaf-eventsubscription.client.prod_url: "https://${client_host}:${client_port}/client"
      nnwdaf-eventsubscription.init: false
      nnwdaf-eventsubscription.prometheus_url: http://${prom_host}:${prom_port}/api/v1/query
      nnwdaf-eventsubscription.containerNames: pg_container,pgadmin4_container,nwdafSub
      SPRING.DATASOURCE.NAME: eventsubscription
      SPRING.DATASOURCE.URL: jdbc:postgresql://db:5434/postgres?currentSchema=public
      SPRING.DATASOURCE.USERNAME: "${POSTGRES_USER}"
      SPRING.DATASOURCE.PASSWORD: "${POSTGRES_PASSWORD}"
      SPRING.DATASOURCE.DRIVERCLASSNAME: org.postgresql.Driver
      EVENTNOTIFICATION.DATASOURCE.NAME: eventnotification
      EVENTNOTIFICATION.DATASOURCE.URL: jdbc:postgresql://db:5434/test?currentSchema=public
      EVENTNOTIFICATION.DATASOURCE.USERNAME: "${POSTGRES_USER}"
      EVENTNOTIFICATION.DATASOURCE.PASSWORD: "${POSTGRES_PASSWORD}"
      EVENTNOTIFICATION.DATASOURCE.DRIVERCLASSNAME: org.postgresql.Driver
      EVENTMETRICS.DATASOURCE.NAME: eventmetrics
      EVENTMETRICS.DATASOURCE.URL: jdbc:postgresql://timescaledb:5433/metrics?currentSchema=public
      EVENTMETRICS.DATASOURCE.USERNAME: "${POSTGRES_USER}"
      EVENTMETRICS.DATASOURCE.PASSWORD: "${POSTGRES_PASSWORD}"
      EVENTMETRICS.DATASOURCE.DRIVERCLASSNAME: org.postgresql.Driver
      SERVER.PORT: "${server_port}"
      management.endpoint.health.show-details: always
      # logging.level.org.hibernate.SQL: DEBUG
      # logging.level.org.hibernate.type.descriptor.sql.BasicBinder: TRACE
      spring.task.scheduling.pool.size: 16
      spring.kafka.bootstrap-servers: ${kafka1_host}:${kafka1_port}
      spring.kafka.consumer.group-id: events
      logging.level.org.apache.kafka: false
      spring.data.redis.host: redis
      spring.data.redis.port: 6379
      nnwdaf-eventsubscription.log.kb: false
      nnwdaf-eventsubscription.log.simple: false
      nnwdaf-eventsubscription.log.sections: false
      nnwdaf-eventsubscription.log.consumer: false
      nnwdaf-eventsubscription.integration.startup: false
      nnwdaf-eventsubscription.integration.nosubs: 20
      nnwdaf-eventsubscription.integration.noclients: 5
      nnwdaf-eventsubscription.integration.resetsubdb: true
      nnwdaf-eventsubscription.integration.resetmetricsdb: false
      nnwdaf-eventsubscription.integration.resetnotifdb: true
      nnwdaf-eventsubscription.integration.cycleSeconds: 100
      nnwdaf-eventsubscription.integration.max_no_cycles: 1
      nnwdaf-eventsubscription.secureWithTrustStore: false
  nwdafSubClient:
    container_name: nwdafSubClient
    image: thanlinardos/nwdaf_sub_client:0.0.2-SNAPSHOT
    restart: always
    tty: true
    ports:
      - "${client_port}:${client_port}"
      - "5007:5007"
    networks:
      - monitor-net
    environment:
      springdoc.enable-native-support: true
      springdoc.swagger-ui.path: /swagger-ui
      server.port: "${client_port}"
      nnwdaf-eventsubscription.openapi.dev_url: "https://${server_host}:${server_port}"
      nnwdaf-eventsubscription.openapi.prod_url: "https://${server_host}:${server_port}"
      nnwdaf-eventsubscription.client.dev_url: "https://${client_host}:${client_port}/client"
      nnwdaf-eventsubscription.client.prod_url: "https://${client_host}:${client_port}/client"
      nnwdaf-eventsubscription.init: false
      #spring configuration:
      spring.datasource.generate-unique-name: false
      spring.datasource.name: eventsubscription
      spring.profiles.active: production
      nnwdaf-eventsubscription.secureWithTrustStore: false

      #endpoints:
      management.endpoint.health.show-details: always
  nwdafSubClient2:
    container_name: nwdafSubClient2
    image: thanlinardos/nwdaf_sub_client:0.0.2-SNAPSHOT
    restart: always
    tty: true
    ports:
      - "${client_port2}:${client_port2}"
      - "5008:5008"
    networks:
      - monitor-net
    environment:
      springdoc.enable-native-support: true
      springdoc.swagger-ui.path: /swagger-ui
      server.port: "${client_port2}"
      nnwdaf-eventsubscription.openapi.dev_url: "https://${server_host}:${server_port}"
      nnwdaf-eventsubscription.openapi.prod_url: "https://${server_host}:${server_port}"
      nnwdaf-eventsubscription.client.dev_url: "https://${client_host2}:${client_port2}/client"
      nnwdaf-eventsubscription.client.prod_url: "https://${client_host2}:${client_port2}/client"
      nnwdaf-eventsubscription.init: false
      #spring configuration:
      spring.datasource.generate-unique-name: false
      spring.datasource.name: eventsubscription
      spring.profiles.active: production
      nnwdaf-eventsubscription.secureWithTrustStore: false

      #endpoints:
      management.endpoint.health.show-details: always
  nwdafSubClient3:
    container_name: nwdafSubClient3
    image: thanlinardos/nwdaf_sub_client:0.0.2-SNAPSHOT
    restart: always
    tty: true
    ports:
      - "${client_port3}:${client_port3}"
      - "5009:5009"
    networks:
      - monitor-net
    environment:
      springdoc.enable-native-support: true
      springdoc.swagger-ui.path: /swagger-ui
      server.port: "${client_port3}"
      nnwdaf-eventsubscription.openapi.dev_url: "https://${server_host}:${server_port}"
      nnwdaf-eventsubscription.openapi.prod_url: "https://${server_host}:${server_port}"
      nnwdaf-eventsubscription.client.dev_url: "https://${client_host3}:${client_port3}/client"
      nnwdaf-eventsubscription.client.prod_url: "https://${client_host3}:${client_port3}/client"
      nnwdaf-eventsubscription.init: false
      #spring configuration:
      spring.datasource.generate-unique-name: false
      spring.datasource.name: eventsubscription
      spring.profiles.active: production
      nnwdaf-eventsubscription.secureWithTrustStore: false

      #endpoints:
      management.endpoint.health.show-details: always
  nwdafSubClient4:
    container_name: nwdafSubClient4
    image: thanlinardos/nwdaf_sub_client:0.0.2-SNAPSHOT
    restart: always
    tty: true
    ports:
      - "${client_port4}:${client_port4}"
      - "5010:5010"
    networks:
      - monitor-net
    environment:
      springdoc.enable-native-support: true
      springdoc.swagger-ui.path: /swagger-ui
      server.port: "${client_port4}"
      nnwdaf-eventsubscription.openapi.dev_url: "https://${server_host}:${server_port}"
      nnwdaf-eventsubscription.openapi.prod_url: "https://${server_host}:${server_port}"
      nnwdaf-eventsubscription.client.dev_url: "https://${client_host4}:${client_port4}/client"
      nnwdaf-eventsubscription.client.prod_url: "https://${client_host4}:${client_port4}/client"
      nnwdaf-eventsubscription.init: false
      #spring configuration:
      spring.datasource.generate-unique-name: false
      spring.datasource.name: eventsubscription
      spring.profiles.active: production
      nnwdaf-eventsubscription.secureWithTrustStore: false

      #endpoints:
      management.endpoint.health.show-details: always
  nwdafSubClient5:
    container_name: nwdafSubClient5
    image: thanlinardos/nwdaf_sub_client:0.0.2-SNAPSHOT
    restart: always
    tty: true
    ports:
      - "${client_port5}:${client_port5}"
      - "5011:5011"
    networks:
      - monitor-net
    environment:
      springdoc.enable-native-support: true
      springdoc.swagger-ui.path: /swagger-ui
      server.port: "${client_port5}"
      nnwdaf-eventsubscription.openapi.dev_url: "https://${server_host}:${server_port}"
      nnwdaf-eventsubscription.openapi.prod_url: "https://${server_host}:${server_port}"
      nnwdaf-eventsubscription.client.dev_url: "https://${client_host5}:${client_port5}/client"
      nnwdaf-eventsubscription.client.prod_url: "https://${client_host5}:${client_port5}/client"
      nnwdaf-eventsubscription.init: false
      #spring configuration:
      spring.datasource.generate-unique-name: false
      spring.datasource.name: eventsubscription
      spring.profiles.active: production
      nnwdaf-eventsubscription.secureWithTrustStore: false

      #endpoints:
      management.endpoint.health.show-details: always
volumes:
  kafka1-data:
  kafka2-data:
  kafka3-data:  
# https://github.com/katyagorshkova/kafka-kraft
      
